export const REMOVE_USER_DATA = 'REMOVE_USER_DATA';
export const STORE_GOAL = 'STORE_GOAL';
export const STORE_GOAL_ALLOCATION = 'STORE_GOAL_ALLOCATION';
export const REMOVE_GOAL_ALLOCATION = 'REMOVE_GOAL_ALLOCATION';
export const STORE_USER_DATA = 'STORE_USER_DATA';
