//This is a theme file, please update any theme related constants here

const COLOR_PRIMARY = '#33CCCC';
const COLOR_PRIMARY_DARK = '#339999';
const COLOR_SECONDARY_DARK = '#D0A954';
const COLOR_SECONDARY = '#DCC853';

const COLOR_DARK = '#000000';
const COLOR_DEFAULT = '#333333';
const COLOR_DEFAULT_LIGHT = '#666666';
const COLOR_LIGHT = '#999999';
const COLOR_LIGHTER = '#AAAAAA';
const COLOR_LIGHTEST = '#DDDDDD';
const COLOR_FADED = '#EEEEEE';
const COLOR_BRIGHT = '#FFFFFF';
const COLOR_TRANSPARENT = 'transparent';

const COLOR_SUCCESS = '#63C208';
const COLOR_DANGER = '#E31912';
const COLOR_WARNING = '#FF9900';

const COLOR_PIN_NUMBER_BG = '#D8E4E0';
const COLOR_EMAIL_CONFIRMATION_BG = '#C0D72F';
const COLOR_COLLECT_ADDITIONAL_INFO_BG = '#1999FF';
const COLOR_COLLECT_ADDRESS_BG = '#FFC858';
const COLOR_COLLECT_DOB_BG = '#ff8754';
const COLOR_CONFIRM_COUNTRY_AND_SOURCE_OF_FUNDS = '#7A8CFF';
const COLOR_UPLOAD_DOCUMENT_BG = '#00D2A3';
const COLOR_COUNTRY_NOT_SUPPORT_AND_WELCOME_ONE_BG = '#6BA7F3';
const COLOR_WELCOME_THIRD_BG = '#b185ed';
const COLOR_BOTTOM_TAB_BG = '#FAFAFA';

export default {
  COLOR_SUCCESS: COLOR_SUCCESS,
  COLOR_DANGER: COLOR_DANGER,
  COLOR_WARNING: COLOR_WARNING,
  COLOR_PRIMARY_DARK: COLOR_PRIMARY_DARK,
  COLOR_PRIMARY: COLOR_PRIMARY,
  COLOR_SECONDARY_DARK: COLOR_SECONDARY_DARK,
  COLOR_SECONDARY: COLOR_SECONDARY,
  COLOR_DEFAULT: COLOR_DEFAULT,
  COLOR_DARK: COLOR_DARK,
  COLOR_DEFAULT_LIGHT: COLOR_DEFAULT_LIGHT,
  COLOR_LIGHT: COLOR_LIGHT,
  COLOR_LIGHTER: COLOR_LIGHTER,
  COLOR_LIGHTEST: COLOR_LIGHTEST,
  COLOR_DISABLED: COLOR_LIGHTER,
  COLOR_FADED: COLOR_FADED,
  COLOR_HINT: COLOR_LIGHTEST,
  COLOR_BRIGHT: COLOR_BRIGHT,
  COLOR_TRANSPARENT: COLOR_TRANSPARENT,
  COLOR_PIN_NUMBER_BG: COLOR_PIN_NUMBER_BG,
  COLOR_EMAIL_CONFIRMATION_BG: COLOR_EMAIL_CONFIRMATION_BG,
  COLOR_COLLECT_ADDITIONAL_INFO_BG: COLOR_COLLECT_ADDITIONAL_INFO_BG,
  COLOR_COLLECT_ADDRESS_BG: COLOR_COLLECT_ADDRESS_BG,
  COLOR_COLLECT_DOB_BG: COLOR_COLLECT_DOB_BG,
  COLOR_CONFIRM_YOUR_COUNTRY_BG: COLOR_CONFIRM_COUNTRY_AND_SOURCE_OF_FUNDS,
  COLOR_UPLOAD_DOCUMENT_BG: COLOR_UPLOAD_DOCUMENT_BG,
  COLOR_COUNTRY_NOT_SUPPORT_BG: COLOR_COUNTRY_NOT_SUPPORT_AND_WELCOME_ONE_BG,
  COLOR_WELCOME_ONE_BG: COLOR_COUNTRY_NOT_SUPPORT_AND_WELCOME_ONE_BG,
  COLOR_WELCOME_THIRD_BG: COLOR_WELCOME_THIRD_BG,
  COLOR_BOTTOM_TAB_BG: COLOR_BOTTOM_TAB_BG,
  INPUT_FIELD_BORDER_COLOR: '#E4E4E4',
  PASSWORD_MEDIUM: COLOR_SECONDARY_DARK, //yellow
  PASSWORD_STRONG: COLOR_SUCCESS, //green
  PASSWORD_WEAK: COLOR_WARNING, // red
  PRIMARY_TEXT_COLOR_DARK: '#282828', //dark gray
  PRIMARY_TEXT_COLOR_LIGHT: '#4A4A4A', // light gray
  QUATERNARY_BACKGROUND_COLOR: COLOR_DARK,
  FONT_LIGHT: 'Roboto-Light',
  FONT_MEDIUM: 'Roboto-Medium',
  FONT_REGULAR: 'Roboto-Regular',
  FONT_BOLD: 'Roboto-Bold',
  SECONDARY_BACKGROUND_COLOR: '#F7C96C', //light yellow
  SECONDARY_TEXT_COLOR_LIGHT: COLOR_BRIGHT, //white
  TERTIARY_BACKGROUND_COLOR: COLOR_BRIGHT,
  TEXT_SIZE_EXTRA_SMALL: 12,
  TEXT_SIZE_SMALL: 14,
  TEXT_SIZE_DEFAULT: 16,
  TEXT_SIZE_MEDIUM: 18,
  TEXT_SIZE_LARGE: 20,
  TEXT_SIZE_EXTRA_LARGE: 24,
};
