export const HIDE_PROGRESS = 'HIDE_PROGRESS';
export const SET_DASHBOARD_SHOWN = 'SET_DASHBOARD_SHOWN';
export const SHOW_PROGRESS = 'SHOW_PROGRESS';
export const UPDATE_PROGRESS_STATE = 'UPDATE_PROGRESS_STATE';
export const STORE_COMPONENT_ID = 'STORE_COMPONENT_ID';
export const REMOVE_COMPONENT_ID = 'REMOVE_COMPONENT_ID';
